theme: jekyll-theme-minimal
title: Guia do CiCalouro da UnB

disciplinas:
- text: Guia Geral do Curso
  url: /geral
- text: Algoritmos e Programação de Computadores
  url: /disciplinas/apc
- text: Introdução aos Sistemas Computacionais
  url: /disciplinas/isc
- text: Fundamentos Teóricos da Computação
  url: /disciplinas/ftc
- text: Informática e Sociedade
  url: /disciplinas/is
- text: Cálculo 1
  url: /disciplinas/c1
