theme: jekyll-theme-minimal
title: Guia do CiCalouro da UnB

disciplinas:
- text: Guia Geral do Curso
  url: /guia-do-cicalouro/geral
- text: Algoritmos e Programação de Computadores
  url: /guia-do-cicalouro/disciplinas/apc
- text: Introdução aos Sistemas Computacionais
  url: /guia-do-cicalouro/disciplinas/isc
# - text: Fundamentos Teóricos da Computação
#   url: /guia-do-cicalouro/disciplinas/ftc
# - text: Informática e Sociedade
#   url: /guia-do-cicalouro/disciplinas/is
- text: Cálculo 1
  url: /guia-do-cicalouro/disciplinas/c1
